language: rust

rust:
    - stable
    - beta
    - nightly
install: 
    - rustup toolchain remove stable && rustup toolchain install stable
    - rustup component add rustfmt --toolchain stable

  jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
